// This file is generated by Slice Machine. Update with care!

import Markdown from './Markdown';
import PageContent from './PageContent';
import TopicList from './TopicList';
import UtilBarLinks from './UtilBarLinks';
import UtilBarTitle from './UtilBarTitle';

export {
	Markdown,
	PageContent,
	TopicList,
	UtilBarLinks,
	UtilBarTitle,
};

export const components = {
	markdown: Markdown,
	page_content: PageContent,
	topic_list: TopicList,
	util_bar_links: UtilBarLinks,
	util_bar_title: UtilBarTitle,
};
